# Generated by Django 3.1.1 on 2020-10-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_dated']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_data']},
        ),
    ]
